# Generated by Django 5.1.1 on 2024-10-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0058_discipline_hospitaltype_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=300)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.area')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.discipline')),
                ('hospital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.hospitaltype')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sector')),
            ],
            options={
                'verbose_name_plural': 'CDB Entries',
            },
        ),
    ]
