# Generated by Django 5.1.1 on 2024-11-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdb', '0003_cdbentry_owner_alter_cdbentry_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdbentry',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
