# Generated by Django 5.1.1 on 2024-10-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0059_entry_discipline_entry_hospital_type_entry_landmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='tp.purposetype')),
            ],
            options={
                'unique_together': {('name', 'purpose_type')},
            },
        ),
        migrations.CreateModel(
            name='TPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=300)),
                ('schedule', models.DateTimeField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.area')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.discipline')),
                ('hospital_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.hospitaltype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tp_entries', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='crm.product')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp.purpose')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sector')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.stage')),
            ],
            options={
                'verbose_name_plural': 'TP Entries',
            },
        ),
    ]
