# Generated by Django 5.1.1 on 2024-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0002_alter_tpentry_purpose_alter_tpentry_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpentry',
            name='landmark',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
