# Generated by Django 5.1.1 on 2024-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0003_alter_tpentry_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpentry',
            name='not_visited',
            field=models.BooleanField(default=False),
        ),
    ]
