# Generated by Django 5.1.1 on 2024-11-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp', '0004_tpentry_not_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpentry',
            name='link',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpentry',
            name='type',
            field=models.CharField(blank=True, choices=[('CRM', 'CRM'), ('CDB', 'CDB'), ('NA', 'NA')], max_length=5),
        ),
    ]
