# Generated by Django 5.1.1 on 2024-09-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_area_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='crm.state'),
        ),
    ]
