# Generated by Django 5.1.1 on 2024-09-24 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_area_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='win',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
