# Generated by Django 5.1.1 on 2024-09-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_administrator_doctor_entry_administrator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='administrator',
            new_name='administrators',
        ),
    ]
