# Generated by Django 5.1.1 on 2024-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_area_state_alter_area_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alcon',
        ),
        migrations.DeleteModel(
            name='DC_FY',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
