# Generated by Django 5.1.1 on 2024-09-26 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_delete_alcon_delete_dc_fy_delete_source_entry_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='laser',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='micro',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='phaco',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='spec',
        ),
        migrations.AlterField(
            model_name='entry',
            name='va',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='entry',
            name='vitrec',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='wide',
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.category')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='products',
            field=models.ManyToManyField(blank=True, to='crm.product'),
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.DeleteModel(
            name='Laser',
        ),
        migrations.DeleteModel(
            name='Micro',
        ),
        migrations.DeleteModel(
            name='Phaco',
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
        migrations.DeleteModel(
            name='VA',
        ),
        migrations.DeleteModel(
            name='Vitrec',
        ),
        migrations.DeleteModel(
            name='Wide',
        ),
    ]
