# Generated by Django 5.1.1 on 2024-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_category_remove_entry_auto_remove_entry_laser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=0, help_text='Set the order for this stage.'),
        ),
    ]
