# Generated by Django 5.1.1 on 2024-09-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_stage_options_stage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
