# Generated by Django 5.1.1 on 2024-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='source',
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.ManyToManyField(blank=True, to='crm.source'),
        ),
    ]
