# Generated by Django 5.1.1 on 2024-09-27 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_source_remove_entry_source_entry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
