# Generated by Django 5.1.1 on 2024-09-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_entry_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='va',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
