# Generated by Django 5.1.1 on 2024-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_entry_va'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
