# Generated by Django 5.1.1 on 2024-10-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_district_state_remove_area_state_area_district_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(default='-1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('code', 'state')},
        ),
    ]
