# Generated by Django 5.1.1 on 2024-10-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_area_options_alter_district_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
