# Generated by Django 5.1.1 on 2024-10-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_entry_institute_delete_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='doctors',
        ),
    ]
