# Generated by Django 5.1.1 on 2024-10-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_remove_entry_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.doctor')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.entry')),
            ],
            options={
                'unique_together': {('entry', 'doctor')},
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='doctors',
            field=models.ManyToManyField(blank=True, through='crm.EntryDoctor', to='crm.doctor'),
        ),
    ]
