# Generated by Django 5.1.1 on 2024-10-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_entrydoctor_entry_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='source',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='administrators',
        ),
        migrations.AddField(
            model_name='administrator',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='crm.entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='crm.entry'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='crm.entry')),
            ],
        ),
        migrations.DeleteModel(
            name='EntryDoctor',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
