# Generated by Django 5.1.1 on 2024-10-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_entry_doctors_remove_entry_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
