# Generated by Django 5.1.1 on 2024-10-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_entry_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
