# Generated by Django 5.1.1 on 2024-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='products',
            field=models.ManyToManyField(to='crm.product'),
        ),
    ]
