# Generated by Django 5.1.1 on 2024-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_entry_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['stage'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
    ]
