# Generated by Django 5.1.1 on 2024-10-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='background_color',
        ),
        migrations.AddField(
            model_name='product',
            name='text_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
