# Generated by Django 5.1.1 on 2024-10-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_rename_color_product_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text_color',
        ),
        migrations.AddField(
            model_name='category',
            name='background_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
