# Generated by Django 5.1.1 on 2024-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_remove_product_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='background_color',
        ),
        migrations.AlterField(
            model_name='category',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
