# Generated by Django 5.1.1 on 2024-10-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_remove_category_background_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='Set the order for this product category.'),
        ),
    ]
