# Generated by Django 5.1.1 on 2024-10-18 10:36

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Entry = apps.get_model('crm', 'Entry')
    ProductEntry = apps.get_model('crm', 'ProductEntry')
    for entry in Entry.objects.all():
        for product in entry.products.all():
            ProductEntry(
                entry=entry,
                product=product,
                count=1,
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_productentry'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
