# Generated by Django 5.1.1 on 2024-10-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_auto_20241018_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='products',
        ),
    ]
