# Generated by Django 5.1.1 on 2024-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_remove_entry_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='products',
            field=models.ManyToManyField(through='crm.ProductEntry', to='crm.product'),
        ),
    ]
