# Generated by Django 5.1.1 on 2024-10-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_entry_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productentry',
            options={'verbose_name_plural': 'ProductEntries'},
        ),
        migrations.AddField(
            model_name='product',
            name='va',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='va',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=3),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='crm.entry'),
        ),
    ]
