# Generated by Django 5.1.1 on 2024-10-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_remove_entry_va_product_cutoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='crm.product'),
        ),
    ]
