# Generated by Django 5.1.1 on 2024-10-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_alter_productentry_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cutoff',
            field=models.BigIntegerField(verbose_name='Cutoff (Incl. GST)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='va',
            field=models.BigIntegerField(),
        ),
    ]
