# Generated by Django 5.1.1 on 2024-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_alter_product_cutoff_alter_product_va'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='va',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
