# Generated by Django 5.1.1 on 2024-10-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_alter_product_va'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='va',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Purchase Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cutoff',
            field=models.PositiveBigIntegerField(verbose_name='Cutoff (Incl. GST)'),
        ),
    ]
