# Generated by Django 5.1.1 on 2024-10-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_remove_product_va_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category']},
        ),
    ]
