# Generated by Django 5.1.1 on 2024-10-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
    ]
