# Generated by Django 5.1.1 on 2024-10-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_stagegroup_stage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagegroup',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
