# Generated by Django 5.1.1 on 2024-10-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_stagegroup_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Dealer Price'),
            preserve_default=False,
        ),
    ]
