# Generated by Django 5.1.1 on 2024-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_product_dealer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dealer_price',
            field=models.PositiveBigIntegerField(verbose_name='Sub Dealer Price'),
        ),
    ]
