# Generated by Django 5.1.1 on 2024-10-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_alter_product_dealer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quoted_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Quoted Price'),
            preserve_default=False,
        ),
    ]
