# Generated by Django 5.1.1 on 2024-10-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_discipline_hospitaltype_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.discipline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='hospital_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='crm.hospitaltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='landmark',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='sector',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crm.sector'),
            preserve_default=False,
        ),
    ]
