# Generated by Django 5.1.1 on 2024-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_entry_discipline_entry_hospital_type_entry_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='landmark',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
