# Generated by Django 5.1.1 on 2024-11-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_brochure'),
        ('crm', '0061_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_products', to='base.brochure'),
        ),
    ]
