# Generated by Django 5.1.1 on 2024-11-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_remove_entry_schedule_date_entry_has_been_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='products',
            field=models.ManyToManyField(related_name='entries', through='crm.ProductEntry', to='crm.product'),
        ),
        migrations.CreateModel(
            name='ExecutedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_va', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
            options={
                'ordering': ['product__category', 'product__name'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='executed_products',
            field=models.ManyToManyField(related_name='entries', to='crm.executedproduct'),
        ),
    ]
