# Generated by Django 5.1.1 on 2024-11-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_alter_entry_products_executedproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executedproduct',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='executedproduct',
            old_name='total_va',
            new_name='va',
        ),
    ]
