# Generated by Django 5.1.1 on 2024-11-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_remove_entry_executed_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='is_selected',
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('custom_va', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='crm.entry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='crm.product')),
            ],
            options={
                'verbose_name_plural': 'Executions',
            },
        ),
    ]
