# Generated by Django 5.1.1 on 2024-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_remove_productentry_is_selected_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='execution_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productentry',
            name='execution_va',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='productentry',
            name='has_execution',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Execution',
        ),
    ]
