# Generated by Django 5.1.1 on 2024-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_productentry_execution_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productentry',
            name='execution_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='execution_va',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
