# Generated by Django 5.1.1 on 2024-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_stage_tracks_tp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='has_been_sent_to_tp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tracks_tp_link',
            field=models.BooleanField(default=False, verbose_name='Track for TP?'),
        ),
    ]
