# Generated by Django 5.1.1 on 2024-12-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_entry_has_been_sent_to_tp_alter_stage_tracks_tp_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='execution_count',
            new_name='booking_count',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='execution_va',
            new_name='booking_va',
        ),
        migrations.RenameField(
            model_name='productentry',
            old_name='has_execution',
            new_name='has_booking',
        ),
    ]
