# Generated by Django 5.1.1 on 2024-12-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_rename_execution_count_productentry_booking_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='has_been_executed',
            new_name='has_been_booked',
        ),
    ]
