# Generated by Django 5.1.1 on 2024-12-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_rename_has_been_executed_entry_has_been_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='has_been_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productentry',
            name='execution_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productentry',
            name='execution_va',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='productentry',
            name='has_execution',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
