# Generated by Django 5.1.1 on 2024-12-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_entry_has_been_executed_productentry_execution_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_in_demo',
            field=models.BooleanField(default=False),
        ),
    ]
