# Generated by Django 5.1.1 on 2025-01-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0075_entry_is_in_demo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={},
        ),
    ]
