# Generated by Django 5.1.1 on 2025-01-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0076_alter_entry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"ordering": ["stage"], "verbose_name_plural": "Entries"},
        ),
    ]
