# Generated by Django 5.1.1 on 2024-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_setting_description_alter_setting_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifying_name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
