# Generated by Django 5.1.1 on 2024-12-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoentry',
            name='notes',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
