# Generated by Django 5.1.1 on 2024-12-16 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_entry_is_in_demo'),
        ('demo', '0004_alter_demoentrynotes_demo_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoentry',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.entry'),
        ),
    ]
