# Generated by Django 5.1.1 on 2024-12-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_entry_is_in_demo'),
        ('demo', '0005_demoentry_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoentry',
            name='product',
        ),
        migrations.CreateModel(
            name='DemoProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='demo.demoentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
    ]
