# Generated by Django 5.1.1 on 2025-01-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0006_remove_demoentry_product_demoproductentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoentry",
            name="notes",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.DeleteModel(
            name="DemoEntryNotes",
        ),
    ]
