name: CI/CD for BhartiSurgitechManagementSystem

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Django settings for dev branch
        if: github.ref == 'refs/heads/dev'
        run: echo "DJANGO_SETTINGS_MODULE=BhartiManagementSystem.settings.dev" >> $GITHUB_ENV

      - name: Set Django settings for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "DJANGO_SETTINGS_MODULE=BhartiManagementSystem.settings.prod" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python manage.py test

          
